# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - machine-azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_91d1f6de597b407aa40ea051f2814093 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d7d354a46605448dbd86eade3e2c6a6c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_91d1f6de597b407aa40ea051f2814093 }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'machine-azure'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_523e9329009045e8b461a8d9ff6a4bdb }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_91d1f6de597b407aa40ea051f2814093 }}/appsvc/wordpress-alpine-php:${{ github.sha }}'